In [4]:
import numpy as np
import cadquery as cq
import gmsh
from microgen import *

In [5]:
nx=30
ny=30
nz=30

x_ = np.linspace(0., 1., nx)
y_ = np.linspace(0., 1., ny)
z_ = np.linspace(0., 1., nz)

x, y, z = np.meshgrid(x_, y_, z_, indexing='ij')

print(x)
print(y)

[[[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  ...
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]]

 [[0.03448276 0.03448276 0.03448276 ... 0.03448276 0.03448276 0.03448276]
  [0.03448276 0.03448276 0.03448276 ... 0.03448276 0.03448276 0.03448276]
  [0.03448276 0.03448276 0.03448276 ... 0.03448276 0.03448276 0.03448276]
  ...
  [0.03448276 0.03448276 0.03448276 ... 0.03448276 0.03448276 0.03448276]
  [0.03448276 0.03448276 0.03448276 ... 0.03448276 0.03448276 0.03448276]
  [0.03448276 0.03448276 0.03448276 ... 0.03448276 0.03448276 0.03448276]]

 [[0.06896552 0.06896552 0.06896552 ... 0.06896552 0.06896552 0.06896552]
  [0.06896552 0.068965

In [6]:
#Size of the mesh
size_mesh = 0.03
a = 1.0
b = 1.0
c = 1.0

periodicity = 0
Revel = rve(a,b,c,size_mesh)
phases = []

S = BasicGeometry(101,'ellipsoid', 0.5, 0.5, 0.5, 0, 0, 0, [0.3, 0.3, 0.4], '')
elli = S.generate()

listSolids = elli.Solids()

In [7]:
from jupyter_cadquery import show, set_defaults, open_viewer
from jupyter_cadquery.replay import enable_replay, disable_replay, reset_replay, get_context, replay, Replay, _CTX
from jupyter_cadquery.cad_objects import to_assembly

cv = open_viewer("Box", cad_width=640, height=480)

Overwriting auto display for cadquery Workplane and Shape


In [8]:
set_defaults(reset_camera=True, show_parent=False, axes=True, axes0=True)

In [10]:
show(listSolids[0])

IndexError: list index out of range